name: Product Submission
description: Submit your product
title: "[Product] <title>"
labels: [Product]
body:

- type: input
  attributes:
    label: Student Name(s)
    description: Add names of all team members.
  validations:
    required: true
    
- type: input
  attributes:
    label: Student GitHub Usernames
    description: Add names of all team members.
  validations:
    required: true

- type: input
  attributes:
    label: University Name
    description: Add university name of all team members. 
  validations:
    required: true


- type: input
  attributes:
    label: Product Name
    description: Please add a name to your product.
  validations:
    required: true

- type: dropdown
  attributes:
    label: Theme
    description: Select a theme for your solution
    options:
      - Sustainability 
      - Healthcare
      - Emerging Technologies
      - Open Innovation
  validations:
    required: true



- type: textarea
  attributes:
    label: Product Description
    description: Please keep your description below 100 characters
  validations:
    required: true

- type: dropdown
  attributes:
    label: GitHub Student Developer Pack Tools Used
    description: |
      Projects must use at least one tool from the Pack.
    multiple: true
    options:
      - Canva
      - Namecheap
      - Microsoft Azure
      - JetBrains
      - Educative
      - Digital Ocean
      - Name.com
      - GitHub Pages
      - Bootstrap Studio
      - GitHub
      - .TECH
      - DataCamp
      - FrontendMasters
      - StreamYard
      - Termius
      - Iconscout
      - GitKraken
      - OneMonth
      - PomoDone
      - EducationHost
      - Repl.it
      - Atom
      - Testmail
      - Covalence
      - Icons8
      - MongoDB
      - New Relic
      - Next.tech
      - InterviewCake
      - Twilio
      - GitHub Desktop
      - Arduino
      - Typeform
      - Polypane
      - GoRails
      - PopSQL
      - Netwise
      - Stripe
      - HazeOver
      - Thinkful
      - Pageclip
      - Sentry
      - Kodika
      - Datadog
      - Imgbot
      - Mailgun
      - Travis CI
      - DeepSource
      - Dashlane
      - Xojo
      - WorkingCopy
      - Gitpod
      - BrowserStack
      - Cryptolens
      - Adafruit
      - Freshpaint
      - Tower
      - Themeisle
      - Restyled
      - Blockchair
      - Blackfire
      - SQLGate
      - Drovio
      - LambdaTest
      - DeepScan
      - Zyte
      - Customerly
      - SymfonyCasts
      - Vaadin
      - CARTO
      - Codecov
      - DailyBot
      - Sider
      - Lingohub
      - AccessLint
      - Weglot
      - NetLicensing
      - Kaltura
      - SOFY
      - Simple Analytics
      - PushBots
      - Wisej
      - Algolia
      - BetterCodeHub
      - Baremetrics
      - Yakindu
      - POEditor
      - Crowdin
      - ConfigCat
      - EverSQL
      - AstraSecurity
      - Transifex
      - Honeybadger
      - Appfigures
      - SQLSmash
      - Phrase
      - Transloadit
      - Raygun
      - Coveralls
      - LogDNA
  validations:
    required: true


- type: input
  attributes:
    label: GitHub Repository URL
    description: Please share GitHub repository link of your project.
  validations:
    required: true
    
- type: input
  attributes:
    label: Project URL
    description: Please share demo link of your project or demo video.
  validations:
    required: true
    
- type: textarea
  attributes:
    label: Product Pitch/Presentation
    description: |
      Links? References? Anything that will give us more context about your project!
      Tip: You can attach project details - pdf files, project presentation, images by clicking this area to highlight it and then dragging files in.
  validations:
    required: true
    
